version: '3.7'

services:
  nginx_cashbox:
    image: nginx:latest
    ports:
      - "8003:80"
    volumes:
      - ./:/var/www/cashbox
      - ./docker/nginx/cashbox.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/cashbox
    depends_on:
      - php7.2-fpm-mongo
    container_name: nginxCashbox
    networks:
      - mongo_network

  php7.2-fpm-mongo:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www/cashbox
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/cashbox
    depends_on:
      - mongo_cashbox
    container_name: php7.2-fpm-mongo
    networks:
      - mongo_network

  mongo_cashbox:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    container_name: mongoCashbox
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - persistent:/data/db
    networks:
      - mongo_network

volumes:
  persistent:
    name: mongoCashboxVolume

networks:
  mongo_network:
    driver: bridge
    name: mongo_network