version: "3.8"

services:
  nginx-cashbox:
    image: nginx:4.2
    ports:
      - "8003:80"
    volumes:
      - ./:/var/www/cashbox
      - ./docker/nginx/cashbox.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/cashbox
    depends_on:
      - php7.4-fpm-cashbox
    container_name: nginx-cashbox
    networks:
      - network-cashbox

  php7.4-fpm-cashbox:
    build:
      context: docker/php-fpm
      args:
        PUID: 1000
        PGID: 1000
        USER: user
    volumes:
      - ./:/var/www/cashbox
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/cashbox
    depends_on:
      - mongo-cashbox
    container_name: php7.4-fpm-cashbox
    user: "1000:1000"
    networks:
      - network-cashbox

  mongo-cashbox:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    container_name: mongo-cashbox
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - persistent:/data/db
    networks:
      - network-cashbox

volumes:
  persistent:
    name: mongoCashboxVolume

networks:
  network-cashbox:
    driver: bridge
    name: network-cashbox