# src/Cashbox/BoxBundle/Resources/config/doctrine/SberbankTransaction.mongodb.yml
Cashbox\BoxBundle\Document\SberbankTransaction:
    fields:
        id:
            id:  true
        datetime:
            type: date
        Sum:
            type: float
        customerNumber:
            type: string
        email:
            type: string
        dataPost:
            type: hash