# src/Cashbox/BoxBundle/Resources/config/doctrine/YandexTransaction.mongodb.yml
Cashbox\BoxBundle\Document\YandexTransaction:
    fields:
        id:
            id:  true
        datetime:
            type: date
        action:
            type: string
        Sum:
            type: float
        email:
            type: string
        dataPost:
            type: hash