# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    Cashbox\BoxBundle\:
        resource: '../../src/Cashbox/BoxBundle/*'
        exclude: '../../src/Cashbox/BoxBundle/{Entity,Document,DependencyInjection,Service,Repository,Tests}'

    Cashbox\UserBundle\:
        resource: '../../src/Cashbox/UserBundle/*'
        exclude: '../../src/Cashbox/UserBundle/{Entity,Document,Repository,Tests}'
