services:
#    box.example:
#        class: Cashbox\BoxBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    admin.organization:
        class: Cashbox\BoxBundle\Admin\OrganizationAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\Organization
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.settings"
              label: "label.organization"
              show_mosaic_button: false
        calls:
            - [ setTemplate, [edit, "BoxBundle:Admin/sonataproject/CRUD:base_edit_form.html.twig"]]

    admin.yandex:
        class: Cashbox\BoxBundle\Admin\YandexTransactionAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\YandexTransaction
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.transactions"
              label: "label.yandex.transactions"
              show_mosaic_button: false

    admin.sberbank:
        class: Cashbox\BoxBundle\Admin\SberbankTransactionAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\SberbankTransaction
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.transactions"
              label: "label.sberbank.transactions"
              show_mosaic_button: false

    admin.komtet:
        class: Cashbox\BoxBundle\Admin\ReportKomtetAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\ReportKomtet
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.komtet"
              label: "label.komtet.report"
              show_mosaic_button: false 

    admin.payment:
        class: Cashbox\BoxBundle\Admin\PaymentAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\Payment
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.payment"
              label: "label.payment"
              show_mosaic_button: false

    admin.other:
        class: Cashbox\BoxBundle\Admin\OtherAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\Other
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.other"
              label: "label.other"
              show_mosaic_button: false

    admin.kkm:
        class: Cashbox\BoxBundle\Admin\KKMAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\KKM
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.KKM"
              label: "label.KKM"
              show_mosaic_button: false