services:
#    box.example:
#        class: Cashbox\BoxBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    admin.organization:
        class: Cashbox\BoxBundle\Admin\OrganizationAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\Organization
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.settings"
              label: "label.organization"
              show_mosaic_button: false
        calls:
            - [ setTemplate, [edit, "BoxBundle:Admin/sonataproject/CRUD:base_edit_form.html.twig"]]

    admin.payment:
        class: Cashbox\BoxBundle\Admin\PaymentAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\Payment
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.organization.payment"
              label: "label.organization.payment"
              show_mosaic_button: false

    admin.other:
        class: Cashbox\BoxBundle\Admin\OtherAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\Other
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.organization.other"
              label: "label.organization.other"
              show_mosaic_button: false

    admin.till:
        class: Cashbox\BoxBundle\Admin\TillAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\Till
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.organization.till"
              label: "label.organization.till"
              show_mosaic_button: false

    #
    # Register
    #
    admin.transaction:
        class: Cashbox\BoxBundle\Admin\Register\TransactionAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\Transaction
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.register"
              label: "label.transactions"
              show_mosaic_button: false

    admin.report.till:
        class: Cashbox\BoxBundle\Admin\Register\TillReportAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\TillReport
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.register"
              label: "label.till.report"
              show_mosaic_button: false

    #
    # Report
    #
    admin.report:
        class: Cashbox\BoxBundle\Admin\Report\ReportAdmin
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: Reports
              label: Reports
        arguments:
            - ~
            - ~
            - Cashbox:Report