services:
#    yandex_box.example:
#        class: Cashbox\BoxBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    admin.organization:
        class: Cashbox\BoxBundle\Admin\OrganizationAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\Organization
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.settings"
              label: "label.organization"
              show_mosaic_button: false
        public: true

    admin.yandex:
        class: Cashbox\BoxBundle\Admin\YandexTransactionAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\YandexTransaction
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.transactions"
              label: "label.yandex.transactions"
              show_mosaic_button: false

    admin.sberbank:
        class: Cashbox\BoxBundle\Admin\SberbankTransactionAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\SberbankTransaction
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.transactions"
              label: "label.sberbank.transactions"
              show_mosaic_button: false 

    admin.komtet:
        class: Cashbox\BoxBundle\Admin\ReportKomtetAdmin
        arguments:
            - ~
            - Cashbox\BoxBundle\Document\ReportKomtet
            - ~
        tags:
            - name: sonata.admin
              manager_type: doctrine_mongodb
              group: "group.komtet"
              label: "label.komtet.report"
              show_mosaic_button: false 
        public: true

    cashbox.mailer:
        class: 'Cashbox\BoxBundle\DependencyInjection\Mailer'
        public: true
        arguments:
          - '%mailer_user%'
          - '@templating'
          - '@mailer'