sonata_admin:
    title: Касса
    search: false
    templates:
        # default global templates
        layout:  BoxBundle:Admin:standard_layout.html.twig
    assets:
        extra_stylesheets:
            - bundles/box/Admin/admin.css
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata.page.register]

            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata.page.settings]

        groups:
            sonata.page.settings:
                label: group.settings
                items:
                    - admin.organization

            sonata.page.register:
                label: group.register
                items:
                    - admin.transaction
                    - admin.report.kkm

            sonata.page.report:
                keep_open: false
                label: labels.groups.reports
                items:
                    - admin.report
                    - route: report_period
                      label: labels.groups.report.period